### ISSUE TITLE
Allow namespaceSelector and selector for resource propagation

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/hierarchical-namespaces#110]
Currently when a resource type is propagated, it's possible to limit this propagation from the resource itself with the `propagate.hnc.x-k8s.io/{select,treeSelect,none}` annotations, i.e to opt-out.

It would be great to also allow to select parent resources with selector, i.e to opt-in:

```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
metadata:
  name: config
spec:
  resources:
    - resource: secrets
      mode: Propagate
      namespaceSelector:
        matchLabels:
          propagate-my-secrets: 'true'
        # matchExpressions:
        #   - key: propagate-my-secrets
        #     operator: Exists
      selector:
        # matchLabels:
        #   propagate-me: 'true'
        matchExpressions:
          - key: propagate-me
            operator: Exists
```
