### ISSUE TITLE
not propagating secrets of type "kubernetes.io/service-account-token"

### ISSUE THREAD

**Issue by santinoncs** [kubernetes-sigs/hierarchical-namespaces#114]
Hi,

I am noticing that when propagating secrets and serviceaccounts

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
...
spec:
  resources:
  - resource: serviceaccounts
  - resource: secrets
status:
  resources:
  - group: ""
    mode: Propagate
    numPropagatedObjects: 14
    numSourceObjects: 21
    resource: secrets
    version: v1
```

the secrets of type kubernetes.io/service-account-token
are not being propagated

You can see that there are 21 secrets and it is only propagating 14

These 7 left are the tokens of the serviceaccounts

is that right?
