### ISSUE TITLE
Metrics svc port mismatch on the release/installation file

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes-sigs/hierarchical-namespaces#115]
The target port on the metrics service should be `8080` or `metrics` instead of `https` as shown below. 

```yaml
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: metrics
```

Since the k8s manifest has the `targetPort: https` the metrics are not scraped by the Prometheus as there isn't any port on that name specified in the service.
