### ISSUE TITLE
How to create a nested subnamespace without failure?

### ISSUE THREAD

**Issue by snagasawa** [kubernetes-sigs/hierarchical-namespaces#117]
Hi,

I want to create nested subnamespace.
The following is sample manifest.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: parent
---
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: child
  namespace: parent
---
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: grandchild
  namespace: child
```

```
$ kubectl hns tree parent
parent
└── [s] child
    └── [s] grandchild
```

However, it always fails the first time.
```
$ kubectl apply -f sample.yaml
namespace/parent created
subnamespaceanchor.hnc.x-k8s.io/child created
Error from server (NotFound): error when creating "subnamespaceanchor.yaml": namespaces "child" not found
```

The second time is successful.
```
$ kubectl apply -f sample.yaml
namespace/parent unchanged
subnamespaceanchor.hnc.x-k8s.io/child unchanged
subnamespaceanchor.hnc.x-k8s.io/grandchild created
```

How to avoid failing?

**Comment by adrianludwin** [comment]
Sorry for the delay in getting back to you. The basic problem here is that you can't create an object in a namespace until the namespace itself has been created. I _think_ that kubectl is smart enough to know that in a single yaml file, if there's a namespace, it should create that first and then create everything in it, but kubectl doesn't know about HNC. So it creates the anchor in the first namespace, but then you need to wait for _HNC_ to create the second namespace, which doesn't happen instantly. That's why the `apply` fails the first time, but succeeds the second time - in between, HNC created the actual namespace.

However, there's another way. You only need to use Subnamespaces if you _don't_ have permission to create _real_ namespaces - which in your case, you clearly do. So you can just create all three namespaces up-front, and then modify the `HierarchyConfiguration` object in `child` to point to `parent`, and in `grandchild` to point to `child`, something like this:

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchyConfiguration
metadata:
  name: hierarchy # the name of the object must _always_ be "hierarchy"
  namespace: child
spec:
  parent: parent
```

You can read about this [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#use-full) and [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#basic-subns).

Hope this helps! Please re-open this bug if you have more questions, or feel free to ask on Slack.

/close
