### ISSUE TITLE
SubnamespaceAnchor status should indicate errors reconciling labels/annotations

### ISSUE THREAD

**Issue by erikgb** [kubernetes-sigs/hierarchical-namespaces#175]
I did a manual test of the new feature introduced in https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/149, and even if this feature is marked as _beta_, I think the user feedback must be improved.

Given a default configuration of HNC, which does not allow any managed labels/annotations, I created a `SubnamespaceAnchor`. Initially I did not try to manage any namespace labels nor annotations:
````yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: child
  namespace: parent
````

The child namespace is created successfully.

Then I modify the `SubnamespaceAnchor`, trying to add one label and one annotation to the child namespace:
````yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: child
  namespace: parent
spec:
  annotations:
  - key: annot-key
    value: annot-value
  labels:
  - key: label-key
    value: label-value
````

The resource is updated successfully, and the status indicates a successful reconcile: 
````yaml
status:
  status: Ok
````

But no label or annotation is added to the child namespace. This is expected, but I think the `SubnamespaceAnchor` status should indicate that HNC was unable to reconcile the spec. The log in the HNC controller pod reports the error, but this log is not available to the user (just admins).

Note: Trying to _create_ the `SubnamespaceAnchor` with the label/annotation is correctly denied by the webhook. So this is an update problem.
