### ISSUE TITLE
Security Context

### ISSUE THREAD

**Issue by rgherta** [kubernetes-sigs/hierarchical-namespaces#181]
Successfuly tested restricted namespace enforcing v1.23 and pod security standards

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/enforce: restricted  
    pod-security.kubernetes.io/enforce-version: v1.23
  name: hnc-system

```

Also security context for controller-manager

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: hnc-controller-manager
  namespace: hnc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --webhook-server-port=9443
        - --metrics-addr=:8080
        - --max-reconciles=10
        - --apiserver-qps-throttle=50
        - --excluded-namespace=kube-system
        - --excluded-namespace=kube-public
        - --excluded-namespace=hnc-system
        - --excluded-namespace=kube-node-lease
        - --excluded-namespace=openebs
        - --excluded-namespace=default
        - --excluded-namespace=gitlab-kubernetes-agent
        - --excluded-namespace=cilium-monitoring
        - --enable-internal-cert-management
        - --cert-restart-on-secret-refresh
        command:
        - /manager
        image: gcr.io/k8s-staging-multitenancy/hnc-manager:v1.0.0
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 10
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
...
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]

...
...

```
