### ISSUE TITLE
Annotations ignored for Rancher K8s clusters

### ISSUE THREAD

**Issue by rhessing** [kubernetes-sigs/hierarchical-namespaces#210]
It seems that when creating a child namespace the annotation part is being ignored by HNS.. I believe it's due to this change but not sure:
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/104

For example:
```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  namespace: parent
  name: child-1
  annotations:
    field.cattle.io/projectId: bhsags621:p-0aa0a
```

The annotation above allows the namespace to be added into a project and thus inherit all project resource quotas and user permissions, allowing the user that creates the HNS to use it.. For a Rancher cluster this is a very handy feature as it allows users to create namespaces from YAML code or the kubectl command instead of going into the Rancher UI to create a namespace.

But somehow that annotation is being ignored.
