### ISSUE TITLE
Propagate parent's annotations to child without knowing their value

### ISSUE THREAD

**Issue by ericmenard** [kubernetes-sigs/hierarchical-namespaces#212]
Hi,

My use case is the following, my parent namespace has annotations to activate or not linkerd. These annotations are not static and changes time to time. I need to propagate these annotations with their values to all sub-namespaces. 

I tried using HierarchyConfiguration beta feature with argument option --managed-namespace-annotation=linkerd.io/inject
```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchyConfiguration
metadata:
  name: hierarchy
  namespace: customer-namespaces
spec:
  annotations:
  - key: linkerd.io/inject
    value: enabled
  [...]
```

This configuration works for static values however it doesn't work in environment with dynamic parent namespaces list and linkerd annotations. 

I also tried using HNCConfiguration with propagate, this is exactly look as what I need. But annotation are not supported.

Did I miss something or it is impossible to propagate annotation from parent to child without knowing their value?
Thanks
