### ISSUE TITLE
Control propagation of labels and annotations from SubnamespaceAnchor to Namespace

### ISSUE THREAD

**Issue by adamjohnson01** [kubernetes-sigs/hierarchical-namespaces#218]
We have a use case where we would like to add `labels` and `annotations` to namespaces  but do not want them propagated down the tree. This is useful for Namespace overrides for specific values that are used by our policy engine.

We configure `--managed-namespace-annotation=tenant.config/.*` and want all of these to be propagated but we also have `namespace.config/*` annotations that we would like to be able to set on each `Namespace`. Ideally something like the following.

```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  namespace: parent-namespace
  name: child-namespace
spec:
  annotations:
  # This will be propagated
  - key: tenant.config/env
    value: prd
  # This will be applied to the Namespace but not propagated down the tree
  - key: namespace.config/default-instance-size
    value: large
```

Currently if I try to do this I get the following error 

`The SubnamespaceAnchor "child-namespace" is invalid: spec.annotations: Invalid value: "namespace.config/default-instance-size": not a managed annotation and cannot be configured`

I think that this could potentially be implemented with a flag to allow non-managed annotations and or labels in the [annotation validation function](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e75b22580ce058c99aa17a59d242f65e5dcb4072/internal/config/validator.go#L30)  and the [label validation function](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e75b22580ce058c99aa17a59d242f65e5dcb4072/internal/config/validator.go#L12). I am happy to implement this if it is approved.

**Comment by adrianludwin** [comment]
Hi, sorry for the delay in getting back to you.

The way we currently limit propagation from parents to children is [Exceptions](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#use-limit-propagation). Currently, these only apply to _objects_, but there's a [proposal](https://docs.google.com/document/d/1MrOXZQ3tgTIVPPaXHYea5FTwG5_-UgqRN2fPK5FT2vc/edit#heading=h.qmy6n690bbq) to add the same feature to HRQs. I believe we should use the same mechanism to limit the propagation of labels and annotations.

As a technical note, "non-managed" labels and annotations are exactly that - they are not managed or enforced by HNC, so asking HNC to manage them wouldn't really make sense. But adding a `propagate` field to the managed labels/annotations would be relatively straightforward:

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  namespace: parent-namespace
  name: child-namespace
spec:
  annotations:
  # This will be propagated
  - key: tenant.config/env
    value: prd
  # This will apply to the subnamespace but no others:
  - key: namespace.config/default-instance-size
    value: large
    propagate: none # like propagate.hnc.x-k8s.io/none
```

It's important to make `propagate` a string field, since we might one day want to allow arbitrary selectors, as we do with objects. But we don't need to do that today, and it's fine to say that the only allowed values for `propagate` are "none" and "all".

wdty?
