### ISSUE TITLE
HNC Manager 1.1.0 RC2 removes HierarchyConfiguration.spec.allowCascadingDeletion when value is false

### ISSUE THREAD

**Issue by ciaccotaco** [kubernetes-sigs/hierarchical-namespaces#273]
### Description

HNC Manager v1.1.0 RC2 strips the `HierarchyConfiguration` resources of `spec.allowCascadingDeletion` when the value is set to `false`. When the value is set to `true`, this behavior does not occur.

When using Config Sync in GKE, the resource goes into a reconciliation loop, as the `HierarchyConfiguration` resource constantly has the key/value added back by the reconciler and removed by the HNC controller.

### Versions

| Software                                            | Version                  |
| ----------------------------------- | ------------------ |
| Hierarchical Namespace Controller | v1.1.0 RC2              |
| Google Kubernetes Engine               | v1.23.16-gke.1100 |
| Anthos Config Management             | v1.14.2                   |

### Error

```json
{
    "level": "error",
    "ts": 1680292295.4456463,
    "logger": "hierarchyconfig.reconcile",
    "msg": "while updating apiserver",
    "rid": 16358,
    "ns": "child-namespace"
    "error": "Operation cannot be fulfilled on hierarchyconfigurations.hnc.x-k8s.io \"hierarcy\": the object has been modified; please apply your changes to the latest version and try again"
}
```

### HierarchyConfiguration Resource YAML

```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchyConfiguration
metadata:
  name: hierarchy
  namespace: child-namespace
spec:
  allowCascadingDeletion: false
  parent: parent-namespace
```

### Current Workaround

The current workaround is to have kustomize remove `spec.allowCascadingDeletion` on all child namespaces. That said, I do not know if having the key removed is the same as having the key's value set to false.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: remove
      path: /spec/allowCascadingDeletion
  target:
    group: hnc.x-k8s.io
    kind: HierarchyConfiguration
    namespace: child-.*
```
