### ISSUE TITLE
hierarchicalresourcequota in subns can be bigger then parent ns??

### ISSUE THREAD

**Issue by zhoushuke** [kubernetes-sigs/hierarchical-namespaces#277]
# version
hnc version: v1.1.0-rc2

# overview
there is a parent ns, and have a subns ns called subns in it, sample case like fllowing

# detail
this is parentns
```yaml
Name:  parentns
Namespace:    test
API Version:  hnc.x-k8s.io/v1alpha2
Kind:         HierarchicalResourceQuota
...
Spec:
  Hard:
    requests.cpu:  1
    requests.memory: 2Gi
    limits.cpu:  1
    limits.memory: 2Gi
```

this is subns
```yaml
Name:  subns
Namespace:    test
API Version:  hnc.x-k8s.io/v1alpha2
Kind:         HierarchicalResourceQuota
...
Spec:
  Hard:
    requests.cpu:  2
    requests.memory: 4Gi
    limits.cpu:  2
    limits.memory: 4Gi
```

two yamls can apply successfully to cluster, but can quota in subns be bigger then root ns?? 
after searching for a while, I haven't found anwer about this, is there something I need to know?

# expectation
in most case ,not being is more reasonable
