### ISSUE TITLE
ha experimental pods run on the same node

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#288]
Problem:
In ha-experimental.yaml, the controller-ha pods run on the same node,
whats the point of ha if when one node fails whole app isnt available?

Solution:
add pod affinity
im assuming this is the file that needs changes:
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/config/variants/ha-webhooks-cc/kustomization.yaml

and this is what needs to be added to the pod:
```yaml
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: control-plane
              operator: In
              values:
              - controller-manager-ha
```
