### ISSUE TITLE
HRQ decimal point value cannot be specified

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes-sigs/hierarchical-namespaces#292]
## What happened?
In `HierarchicalResourceQuota`, decimal point value cannot be specified.
It's allowed in `ResourceQuota`.

## What did you expect to happen?
Decimal point value can be specified as `ResourceQuota`

## How can we reproduce it (as minimally and precisely as possible)?
For example, this will be invalid.

`test-hrq.yaml`
```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchicalResourceQuota
metadata:
  name: test-hrq
  namespace: test
spec:
  hard:
    limits.cpu: 1.5	# invalid 
    limits.memory: 500Mi
    requests.cpu: 1
    requests.memory: 200Mi
```

```console
$ kubectl apply -f test-hrq.yaml 
The HierarchicalResourceQuota "test-hrq" is invalid: 
* spec.hard.limits.cpu: Invalid value: "number": spec.hard.limits.cpu in body must be of type integer,string: "number"
* <nil>: Invalid value: "": "spec.hard.limits.cpu" must validate at least one schema (anyOf)
* spec.hard.limits.cpu: Invalid value: "number": spec.hard.limits.cpu in body must be of type integer: "number"
```

If set `limits.cpu: "1.5"`, it works.

**Comment by mochizuki875** [comment]
I couldn't understand the details, but at least it seems that `ResourceQuota.spec.hard` and `HierarchicalResourceQuota.spec.hard` are not exactly the same.

`ResourceQuota.spec.hard`
```console
$ kubectl explain --recursive ResourceQuota.spec.hard 
KIND:       ResourceQuota
VERSION:    v1

FIELD: hard <map[string]Quantity>:

DESCRIPTION:
```

`HierarchicalResourceQuota.spec.hard`
```console
$ kubectl explain --recursive HierarchicalResourceQuota.spec.hard
GROUP:      hnc.x-k8s.io
KIND:       HierarchicalResourceQuota
VERSION:    v1alpha2

FIELD: hard <map[string]Object>:

DESCRIPTION:
```

We reuse [the k8s parsing code](https://github.com/kubernetes/api/blob/1bc03f6ff533896e6c57e5032babe7bdc39848fb/core/v1/types.go#L5550) in `hierarchicalresourcequota_types.go`.
(The `ResourceQuota`'s definition is [here](https://github.com/kubernetes/api/blob/1bc03f6ff533896e6c57e5032babe7bdc39848fb/core/v1/types.go#L6272))

`hierarchicalresourcequota_types.go`
```go
...
type HierarchicalResourceQuotaSpec struct {
	// Hard is the set of desired hard limits for each named resource
	// +optional
	Hard corev1.ResourceList `json:"hard,omitempty"`
}
...
```

However, generated CRD defines the `HierarchicalResourceQuota.spec.hard` as integer or string.

`hnc.x-k8s.io_hierarchicalresourcequotas.yaml`
```yaml
          spec:
            description: Spec defines the desired quota
            properties:
              hard:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
```

So it might have something to do with the process of converting `_types.go ` to CRD by controller-gen.
(Maybe it's a CRD constraint?)
