### ISSUE TITLE
Default subnamespace permissions 

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#317]
Each time when I install HNC I give permissions to the `clusterRole/edit` on the hnc custom resources.
It allows the clients create their own sub namespaces if they have at least edit role:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: hnc-edit
rules:
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - hierarchyconfigurations
  - hierarchicalresourcequotas
  - subnamespaceanchors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - hierarchicalresourcequotas
  - subnamespaceanchors
  verbs:
  - create
  - update
  - patch
  - delete
```

So I'm wondering, should I create a PR so it would be like that by default?
