### ISSUE TITLE
Labels are not added when using SubnamespaceAnchor manifest

### ISSUE THREAD

**Issue by aboncok** [kubernetes-sigs/hierarchical-namespaces#323]
Hi,
As with all other Kubernetes resources, I was expecting to see defined labels on the created subnamespaces too.
Take following manifest for example:
```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: app3
  namespace: hnc-child1
  labels:
    name: app3
    env: hnc-child1
```
Checking the created namespace:
`kubectl describe ns app3`
It shows me this:
```
Name:         app3
Labels:       app3.tree.hnc.x-k8s.io/depth=0
              hnc-child1.tree.hnc.x-k8s.io/depth=1
              hnc-test.tree.hnc.x-k8s.io/depth=2
              hnc.x-k8s.io/included-namespace=true
              kubernetes.io/metadata.name=app3
Annotations:  hnc.x-k8s.io/subnamespace-of: hnc-child1
Status:       Active

No resource quota.

No LimitRange resource.
```
The label is missing.
Labels are an important component in controlling access and managing resources.
Would it be possible to add handling these?

**Comment by adrianludwin** [comment]
Instead of this:

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: app3
  namespace: hnc-child1
  labels: # these are the labels on the anchor itself, not the child namespace
    name: app3
    env: hnc-child1
```

You should use this:

```
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  name: app3
  namespace: hnc-child1
spec:
  labels: # these are the labels that will be created on the child namespace, not the anchor
    name: app3
    env: hnc-child1
```

That is: the anchor _spec_ defines which labels should appear on the newly created namespace. The anchor can have its _own_ labels and annotations, which are separate from those that appear on the subnamespace. This is the same as the template in a Deployment (i.e. [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)). Does that make sense?
