### ISSUE TITLE
propagate clusterRoleBindings objects

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#328]
We are using openshift, and our client has anyuid securityContextConstraint on the service account in the namespace (which is simply clusterRoleBinding for the service account)

When he creates sub-namespaces, the clusterRoleBinding of anyuid is not being propagated, thus his application can't run.

Is there any way to make it possible propagate cluster-wide objects?
maybe add field in HNCConfiguration that specifies which field to change when propagating cluster-wide object, or maybe there is other workaround?

**Comment by zfrhv** [comment]
something like this:
```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
metadata:
  name: config
spec:
  resources:
  - group: rbac.authorization.k8s.io
    resource: clusterrolebindings
    namespaceField: subjects[0].namespace
```
and the name of the propogated object can be randomly generated + label of the namespace.

for example clusterRoleBinding with name test can become test-wgkrvk with label `hnc.x-k8s.io/namespace: child1`
```

**Comment by zfrhv** [comment]
maybe even `namespaceFields` can be an array, and then you can specify multiple paths.

its also good even for namespaced custom resources which have other places where the namespace is mentioned.

let me know what do you think and i will try to make a PR

**Comment by erikgb** [comment]
I don't think this is a problem HNC should solve. SCC is a cluster-scoped resource type. If you need the `anyuid` SCC added to all serviceaccounts, I think you should configure your cluster to do it. But I don't recommend it, as it will break the OpenShift "secure by default" policy.

**Comment by zfrhv** [comment]
hii @erikgb thanks for the reply
i need to give scc only to a specific client and his sub-namespaces

also i was thinking that there may be other objects that somehow related to a namespace and should be propogated

for example OperatorGroup, would be nice to propogate as well. like this:
```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
metadata:
  name: config
spec:
  resources:
  - group: operators.coreos.com
    resource: operatorgroups
    namespaceField: spec.targetNamespaces[0]
```
operatorGroup is a namespaced object, but its not being propogated properly.

so i thought that we can configure the propogation field, and this will also allow us to know how a cluster-wide object can be propogated.
which will solve the clusterRoleBinding problem

there may be other CRDs (cluster-wide or not) that are related to namespace and should be propogated as well (that im not aware of).

**Comment by erikgb** [comment]
I am pretty sure HNC should be able to propagate any namespaced resource - if configured to do so. If this is not the behavior, please report an issue.

But Openshift SCC is a cluster-scoped resource, so IMO **propagate** does not make sense - since it is cluster-scoped.

**Comment by zfrhv** [comment]
> If this is not the behavior, please report an issue.

sounds fair, i will open another case

> But Openshift SCC is a cluster-scoped resource, so IMO propagate does not make sense - since it is cluster-scoped.

im not talking about scc, im talking about cluster wide permission (clusterRoleBinding), if a service account has permissions on some cluster-wide object (like list storageClasses, namespaces, nodes...) then sounds fair to have similar permissions in the sub-namespaces.

i agree that cluster-wide object should be created only once and not per each namespace, but what can be done if cluster-wide permissions cant be namespaced, how to propogate those permissions?

but you have a good point, maybe adding multiple `subjects` in the clusterRoleBinding is better than creating multiple clusterRoleBindings for each namespace.

**Comment by zfrhv** [comment]
#329

**Comment by erikgb** [comment]
> but you have a good point, maybe adding multiple `subjects` in the clusterRoleBinding is better than creating multiple clusterRoleBindings for each namespace.

Yes, that is one way to solve it. Granting access to elevated SCCs is a cluster-admin responsibility IMO.

**Comment by zfrhv** [comment]
Sorry I missed the notification somehow

> Granting access to elevated SCCs is a cluster-admin responsibility IMO.

Yes but there is no way to automate it.
If I could configure the HNCConfiguration to propagate the clusterRoleBinding I would consider it as I'm responsible for it (as long as its propagated as expected)

Seems to me that you dont like the way SCC works, and I dont like it too, but this is an issue about propagation of cluster-wide permissions.

For example (real scenario) I allow my client to list nodes with their application by giving CluterRoleBinding to their serviceAccount:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-list-client1
subjects:
- kind: ServiceAccount
  name: client1-sa
  namespace: client1
roleRef:
  kind: ClusterRole
  name: node-list-role
  apiGroup: rbac.authorization.k8s.io
```
The client has pipeline that automatically creates child subNamespace, creates the application in that child subNamespace, runs tests, and deletes the subNamespace.
Seems like all was good because all the permissions were namespace (roleBindings propagated well).
But then we realized that the application requires to list nodes, and now we are stuck because HNC cant propagate ClusterRoleBinding, and I cant give the client permissions to create ClusterRoleBindings.
