### ISSUE TITLE
propagating operatorGroup doesnt works right

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#329]
when having operatorGroup in parent namespace:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: simple-og
  namespace: parent
spec:
  serviceAccountName: restricted-sa
  targetNamespace:
  - parent
```

and propagating it to a child namespace we get:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: simple-og
  namespace: child
spec:
  serviceAccountName: restricted-sa
  targetNamespace:
  - parent
```
the operatorGroup targets his parent instead of himself.

i suggest to add field `namespaceFields` to the propagation configuration:
```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
metadata:
  name: config
spec:
  resources:
  - group: operators.coreos.com
    resource: operatorgroups
    namespaceFields:
    - spec.targetNamespaces[0]
```
and then HNC will know which other field he needs to modify when propagating.

similar problem may occur in other custom resources that im not aware of
