### ISSUE TITLE
is there an example on how to add managed labels?

### ISSUE THREAD

**Issue by wibed** [kubernetes-sigs/hierarchical-namespaces#342]
i cant seem to get it right, i tried:

- kubectl hns set parent --managed-namespace-label pod-security.kubernetes.io/enforce
- kubectl hns create child -n parent --managed-namespace-label  pod-security.kubernetes.io/enforce

**Comment by adrianludwin** [comment]
There's no command-line tool to set managed labels. You need to modify the `HierarchyConfiguration` object directly. The easiest way to do this from the command line is `kubectl edit -n namespace hierarchyconfiguration hierarchy`, and then edit the labels as shown [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#use-managed-labels).

Generally speaking, almost any kubectl command can be replaced by hand-editing a YAML file and then saying `kubectl apply -f foo.yaml`. As a result, we only tend to add the more common commands to the kubectl plugin. I'd be happy if you or someone else wanted to contribute a patch but I don't have any time for active development myself these days.

Hope this helps!

**Comment by wibed** [comment]
i tried this aswell.

given i edit the hierarchyconfiguration of a subnamespace
it does result in a message not unlike:
`label is not managed, unable to configure.`

**Comment by adrianludwin** [comment]
Oh, I see the confusion - you were looking at [these admin commands](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#admin-managed-labels), right?

The `--managed-namespace-label` command-line flag isn't for the `kubectl` client; it's for the HNC workload that actually runs on the server. You need to _first_ modify the HNC deployment [like this](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#admin-cli-args) to tell HNC which labels/annotations are managed, and only _then_ will you be able to modify the `HierarchyConfiguration` objects.

Does that make sense? I think you got close, you were just missing the last steps.

**Comment by wibed** [comment]
for future generations:


```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0-rc2/default.yaml
  - ./resources

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-label=pod-security.kubernetes.io/enforce
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
```
