### ISSUE TITLE
Possible bug in propagation matching algorithm

### ISSUE THREAD

**Issue by gbmeuk** [kubernetes-sigs/hierarchical-namespaces#343]
When investigating another issue I found I can partially work around the constraint which forces RoleBindings to Propagate by dropping group from the resourced object:
```
spec:
  resources:
    - resource: rolebindings
      mode: AllowPropagate
```
So I suspect there may be a bit of a bug in the matching algorithm. It only partially works though and causes some other component of the system to revert the change frequently.
```
{"level":"info","ts":1698313059.863884,"logger":"hncconfig.reconcile","msg":"Changing sync mode of the object reconciler","gvk":"rbac.authorization.k8s.io/v1, Kind=RoleBinding","oldMode":"AllowPropagate","newMode":"Propagate"}
{"level":"info","ts":1698313059.8659315,"logger":"hncconfig.reconcile","msg":"Changing sync mode of the object reconciler","gvk":"rbac.authorization.k8s.io/v1, Kind=RoleBinding","oldMode":"Propagate","newMode":"AllowPropagate"}
```

There is also  this. Albeit, not exactly a problem but does suggest that the matching needs a review. When I set role bindings to `Propagate` as the value is needs to be, there is still an admission webhook error:
```
spec:
  resources:
    - resource: rolebindings
      mode: Propagate
```
```
admission webhook "hncconfigurations.hnc.x-k8s.io" denied the request: HNCConfiguration.hnc.x-k8s.io "config" is invalid: spec.resources[1]: Invalid value: rolebindings.rbac.authorization.k8s.io: always uses the 'Propagate'
```
