### ISSUE TITLE
ha.yaml contains the same object multiple times

### ISSUE THREAD

**Issue by nikhiljha** [kubernetes-sigs/hierarchical-namespaces#360]
This object appears in ha.yaml twice, with all fields the same. I think kubectl is okay with this but my deployment tooling does not like it :(

For now I wrote a hack that deduplicates it, but this should probably get fixed here too

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager
  name: hnc-controller-manager-metrics-service
  namespace: hnc-system
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    control-plane: controller-manager
```
