### ISSUE TITLE
helm extra controller args

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#385]
hi @mochizuki875
I want to add --unpropagated-label=<string> to the helm chart as mentioned in the docs:
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#admin-managed-labels

should I add something like:
```yaml
manager:
  extraArgs:
  - --unpropagated-label: app.kubernetes.io/instance
```
or something like:
```yaml
manager:
  unpropagatedLabel: app.kubernetes.io/instance
```
?

because there are many other controller arguments

**Comment by mochizuki875** [comment]
@zfrhv 
Sorry for late a response...
IMO, it's preferable like that.

```yaml
manager:
  unpropagatedLabel:
  - app.kubernetes.io/instance
  - example.com/foo
```

Additionally, it might be beneficial to handle `--unpropagated-annotation` similarly, as it appears to have similar characteristics to `--unpropagated-label`.
