### ISSUE TITLE
Issues with `make charts` and `helm install`

### ISSUE THREAD

**Issue by ramiradaideh** [kubernetes-sigs/hierarchical-namespaces#404]
Issues found when running make charts:

1. Running make charts executes the upgrade-helm.sh file. 

The file uses the manifests/default.yaml  to generate the helm chart templates required for hns installation.  The installation fails because resource names are the same and end up generating the same helm template file. 

For example, the following will cause the creation of hnc-resourcelist.yaml for both resources, resulting in one overriding the other.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hnc-resourcelist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hnc-resourcelist
subjects:
- kind: ServiceAccount
  name: default
  namespace: hnc-system
---
apiVersion: v1
kind: Secret
metadata:
  name: hnc-resourcelist
  namespace: hnc-system
```

2.  Error during helm install

After the make chart command above. Running the `helm install hnc .....` produces the following error 

Error: INSTALLATION FAILED: parse error at (hnc/templates/hnc-resourcelist-apiextension.yaml-e:56): unexpected EOF

The upgrade-helm.sh script should have added additional code to the YAML files generated from default.yaml to ensure that all open brackets were properly closed, but this did not occur as expected.

Has anyone faced this issue during installation?
