### ISSUE TITLE
HNC: TLS handshake error from X.X.X.X:YYYY: EOF

### ISSUE THREAD

**Issue by vikas027** [kubernetes-sigs/hierarchical-namespaces#49]
## Environment
- EKS v1.20.6
- HNC 0.8.0

## Problem
HNC controller pod (`hnc-controller-manager-xxxxxx`) is working fine but is throwing a lot of these errors. 
```bash
{"level":"error","ts":1623959262.9720078,"msg":"http: TLS handshake error from 10.50.114.121:33364: EOF"}
{"level":"error","ts":1623959262.9722204,"msg":"http: TLS handshake error from 10.50.114.121:33362: EOF"}
{"level":"error","ts":1623959262.973659,"msg":"http: TLS handshake error from 10.50.114.121:33360: EOF"}
{"level":"error","ts":1623961441.4681904,"msg":"http: TLS handshake error from 10.50.114.121:49344: EOF"}
{"level":"error","ts":1623966001.330808,"msg":"http: TLS handshake error from 10.50.114.121:54676: EOF"}
{"level":"error","ts":1623966658.7782638,"msg":"http: TLS handshake error from 10.50.165.218:38060: EOF"}
{"level":"error","ts":1623966658.7784226,"msg":"http: TLS handshake error from 10.50.165.218:38058: EOF"}
{"level":"error","ts":1623967363.0862052,"msg":"http: TLS handshake error from 10.50.114.121:36362: EOF"}
```

## Similar Issues
- https://github.com/kubernetes-sigs/multi-tenancy/issues/1255

**Comment by adrianludwin** [comment]
Thanks @vikas027 . Turning these into human-readable dates, I get:
```
Thu Jun 17 2021 19:47:42 (x3)
Thu Jun 17 2021 20:24:01
Thu Jun 17 2021 21:40:01
Thu Jun 17 2021 21:50:58 (x2)
Thu Jun 17 2021 22:02:43
```

So maybe about one or two events an hour, with each "event" sometimes showing a couple of messages.

Is this correlated to any other event with HNC? E.g. the pod restarting or anything?

The "EOF" got me suspicious that a connection was just getting dropped, and I found [this SO comment](https://stackoverflow.com/questions/34823724/golang-tls-handshake-error) suggesting that TCP keepalive will fix it. I wonder if it's a similar issue, given that the reporter only noticed it when the connection had been idle for a long time. I could imagine HNC going idle for a while too if it has nothing much to do.

Another possibility is [raising the MTU](https://github.com/kubernetes-sigs/metrics-server/issues/145).

@vikas027 I don't know much (well, anything) about EKS, is it possible to modify any of these params on your cluster and see if it helps?

Failing that, a lot of these messages are created by `controller-runtime` so it would be tricky for us to try to filter them out.

**Comment by vikas027** [comment]
Hey @adrianludwin , 
I am using Bottlerocket as EKS worker nodes where things are pretty locked down and have been optimized to run Kubernetes workloads. I have a lot of applications running and I am not seeing such errors anywhere else, not sure if this an EKS issue. 

Is there a way to increase the verbosity (debug) of the HNC logs?

**Comment by adrianludwin** [comment]
Hmm, no idea. I take it the problem persists?

Can you attach logs (double-check there's no information in there that you don't mind leaking, e.g. namespace names, or just rename them all to "ns1," "ns2" etc) as well as the YAML of the pod? Also, if you could figure out what's at the IP address that's mentioned in the error, that would also be helpful. It seems to be oscillating between two IP addresses (`10.50.165.218` and `10.50.114.121`) but without ever repeating the ports, which is odd.

Finally, if you could confirm that there are, or are not, pod restarts that are correlated with these messages, that might be another clue. Perhaps that's included in your logs.

**Comment by vikas027** [comment]
Hello @adrianludwin ,
I have further digged into those IPs, those are from the default `kubernetes` endpoint which kubernetes creates in the `default` namespace. Please note, I have two clusters behaving exactly and none of them has no workloads running in the `default` namespace.

Not sure where else can I look at :)

```yaml
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 10.50.165.218
  - ip: 10.50.114.121
  ports:
  - name: https
    port: 443
    protocol: TCP
```

Here are some recent logs
```bash
{"level":"error","ts":1624797171.1220329,"msg":"http: TLS handshake error from 10.50.114.121:43166: EOF"}
{"level":"error","ts":1624798611.290382,"msg":"http: TLS handshake error from 10.50.114.121:55270: EOF"}
{"level":"error","ts":1624798611.2905447,"msg":"http: TLS handshake error from 10.50.114.121:55268: EOF"}
{"level":"error","ts":1624799871.090236,"msg":"http: TLS handshake error from 10.50.114.121:37874: EOF"}
{"level":"error","ts":1624799871.0998201,"msg":"http: TLS handshake error from 10.50.114.121:37878: EOF"}
{"level":"error","ts":1624802571.0674863,"msg":"http: TLS handshake error from 10.50.114.121:60824: EOF"}
{"level":"error","ts":1624802931.1300197,"msg":"http: TLS handshake error from 10.50.114.121:35658: EOF"}
{"level":"error","ts":1624804699.2879634,"msg":"http: TLS handshake error from 10.50.165.218:43884: EOF"}
{"level":"info","ts":1624805372.6467125,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"hnc-validating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"hnc-validating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
{"level":"error","ts":1624806491.543539,"msg":"http: TLS handshake error from 10.50.165.218:57936: EOF"}
{"level":"error","ts":1624812291.0658677,"msg":"http: TLS handshake error from 10.50.114.121:59380: EOF"}
{"level":"error","ts":1624812291.3288004,"msg":"http: TLS handshake error from 10.50.114.121:59388: EOF"}
{"level":"error","ts":1624814029.6276171,"msg":"http: TLS handshake error from 10.50.114.121:46364: EOF"}
{"level":"error","ts":1624814091.317666,"msg":"http: TLS handshake error from 10.50.114.121:46876: EOF"}
{"level":"info","ts":1624815480.4014397,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"hnc-validating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"hnc-validating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
{"level":"error","ts":1624815622.1466093,"msg":"http: TLS handshake error from 10.50.114.121:59614: EOF"}
{"level":"error","ts":1624817871.229798,"msg":"http: TLS handshake error from 10.50.114.121:50308: EOF"}
{"level":"error","ts":1624818411.2999148,"msg":"http: TLS handshake error from 10.50.114.121:54924: EOF"}
{"level":"error","ts":1624819131.3163505,"msg":"http: TLS handshake error from 10.50.114.121:60852: EOF"}
{"level":"error","ts":1624820751.2582116,"msg":"http: TLS handshake error from 10.50.114.121:46284: EOF"}
{"level":"error","ts":1624820751.3118231,"msg":"http: TLS handshake error from 10.50.114.121:46288: EOF"}
{"level":"error","ts":1624820751.400276,"msg":"http: TLS handshake error from 10.50.114.121:46292: EOF"}
{"level":"error","ts":1624820751.400447,"msg":"http: TLS handshake error from 10.50.114.121:46294: EOF"}
{"level":"error","ts":1624822526.5999544,"msg":"http: TLS handshake error from 10.50.165.218:44264: EOF"}
{"level":"error","ts":1624825791.5147407,"msg":"http: TLS handshake error from 10.50.114.121:60974: EOF"}
{"level":"error","ts":1624825971.2210906,"msg":"http: TLS handshake error from 10.50.114.121:34206: EOF"}
{"level":"error","ts":1624825971.4480453,"msg":"http: TLS handshake error from 10.50.114.121:34222: EOF"}
{"level":"error","ts":1624826040.053663,"msg":"http: TLS handshake error from 10.50.114.121:34792: EOF"}
{"level":"error","ts":1624826619.948627,"msg":"http: TLS handshake error from 10.50.165.218:48310: EOF"}
{"level":"error","ts":1624829031.4745123,"msg":"http: TLS handshake error from 10.50.114.121:60460: EOF"}
{"level":"error","ts":1624829031.599868,"msg":"http: TLS handshake error from 10.50.114.121:60466: EOF"}
{"level":"error","ts":1624829571.524453,"msg":"http: TLS handshake error from 10.50.114.121:36800: EOF"}
{"level":"error","ts":1624829751.2505043,"msg":"http: TLS handshake error from 10.50.114.121:38314: EOF"}
{"level":"error","ts":1624830291.499894,"msg":"http: TLS handshake error from 10.50.114.121:42838: EOF"}
{"level":"error","ts":1624831191.427693,"msg":"http: TLS handshake error from 10.50.114.121:50540: EOF"}
{"level":"error","ts":1624832631.4050016,"msg":"http: TLS handshake error from 10.50.114.121:34386: EOF"}
{"level":"error","ts":1624833105.3434877,"msg":"http: TLS handshake error from 10.50.114.121:38356: EOF"}
{"level":"error","ts":1624834824.3399158,"msg":"http: TLS handshake error from 10.50.114.121:52850: EOF"}
{"level":"error","ts":1624834824.3400981,"msg":"http: TLS handshake error from 10.50.114.121:52856: EOF"}
```

And here is the my pod configuration
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    app.kubernetes.io/managed-by: argocd
    kubernetes.io/psp: eks.privileged
  labels:
    app: hnc
    control-plane: controller-manager
    pod-template-hash: 5c8bd48cb
    type: platform
  name: hnc-controller-manager-5c8bd48cb-rzjpq
  namespace: hnc-system
spec:
  containers:
  - args:
    - --webhook-server-port=9443
    - --metrics-addr=:8080
    - --max-reconciles=10
    - --apiserver-qps-throttle=50
    - --enable-internal-cert-management
    - --cert-restart-on-secret-refresh
    - --excluded-namespace=kube-system
    - --excluded-namespace=kube-public
    - --excluded-namespace=hnc-system
    - --excluded-namespace=kube-node-lease
    command:
    - /manager
    image: gcr.io/k8s-staging-multitenancy/hnc-manager:v0.8.0
    name: manager
    ports:
    - containerPort: 9443
      name: webhook-server
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        memory: 150Mi
    volumeMounts:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
  - args:
    - --upstream=http://127.0.0.1:8080/
    - --secure-listen-address=0.0.0.0:8443
    - --logtostderr=true
    - --v=10
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: default
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cert
    secret:
      secretName: hnc-webhook-server-cert
```
